name: pytorchtf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - pytorch=1.2.*
  - torchvision
  - cpuonly
  - protobuf
  - pip
  - pip:
    - fastai
    - tensorflow==1.15
    - onnx
    - onnx-tf
