name: pytorchtf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - tensorflow=1.14.*
  - pytorch=1.2.*
  - torchvision
  - cpuonly
  - protobuf
  - onnx
  - pip
  - pip:
    - fastai
    - onnx-tf
